server:
  servlet:
    context-path: /jira
  port: 8081

cloud-session-token: eyJraWQiOiJzZXNzaW9uLXNlcnZpY2VcL3Nlc3Npb24tc2VydmljZSIsImFsZyI6IlJTMjU2In0.eyJhc3NvY2lhdGlvbnMiOltdLCJzdWIiOiI1ZDliYTlkNWNkNTBiODBkY2VhOGIzYWMiLCJlbWFpbERvbWFpbiI6Im15b2IuY29tIiwiaW1wZXJzb25hdGlvbiI6W10sInJlZnJlc2hUaW1lb3V0IjoxNTc2MDMwMzkzLCJ2ZXJpZmllZCI6dHJ1ZSwiaXNzIjoic2Vzc2lvbi1zZXJ2aWNlIiwic2Vzc2lvbklkIjoiY2E5ODY1NWQtM2JlYi00MTQyLTg4ZTUtNzM2YzI3MGJlNDJjIiwiYXVkIjoiYXRsYXNzaWFuIiwibmJmIjoxNTc2MDI5NzkzLCJleHAiOjE1Nzg2MjE3OTMsImlhdCI6MTU3NjAyOTc5MywiZW1haWwiOiJxaWxpbi5sb3VAbXlvYi5jb20iLCJqdGkiOiJjYTk4NjU1ZC0zYmViLTQxNDItODhlNS03MzZjMjcwYmU0MmMifQ.mrIyCzDtHJdkPUHSY0_CXSIhUJ6S76QJAmhVXrk4UnrOsfibpkgdg7co_uCxlBY2lpISi9PD3LPSeIer3-vGIp6iavdGu4P_p7aXQmBLBw32bW48uE81kVwnluuxKWVklnrCx0s0QLLgPSnojXyCBkXOQtxb8NcG-lrIbSrCx6EplzS4qjOS4rehqf4pvSzeWpabuUGIdXuUJu7iMvPV-1l_grqCDwmo8vz78k_uEQMvsVkSCBNZUrFdFfhVw5dFbRB8rakn1J0DT__78ZMPpYxdyFitqbtKJlaEsJ_GuWGResNIDkolxb5Lu2biyUpwRC-MbcAhcLSJSH9diEF-ug

jira-token: Basic cWlsaW4ubG91QG15b2IuY29tOnQySVgxeURyU2VUeHBqc3hJMHhvMEM1Nw==

