server:
  servlet:
    context-path: /jira
  port: 8083

cloud-session-token: eyJraWQiOiJzZXNzaW9uLXNlcnZpY2VcL3Nlc3Npb24tc2VydmljZSIsImFsZyI6IlJTMjU2In0.eyJhc3NvY2lhdGlvbnMiOltdLCJzdWIiOiI1ZDliYTlkNWNkNTBiODBkY2VhOGIzYWMiLCJlbWFpbERvbWFpbiI6Im15b2IuY29tIiwiaW1wZXJzb25hdGlvbiI6W10sInJlZnJlc2hUaW1lb3V0IjoxNTc1NjAxNTA5LCJ2ZXJpZmllZCI6dHJ1ZSwiaXNzIjoic2Vzc2lvbi1zZXJ2aWNlIiwic2Vzc2lvbklkIjoiZTFmOTg4NjctNjYwZS00NmY5LWE5ZGYtNTExMTBkZWNmY2FhIiwiYXVkIjoiYXRsYXNzaWFuIiwibmJmIjoxNTc1NjAwOTA5LCJleHAiOjE1NzgxOTI5MDksImlhdCI6MTU3NTYwMDkwOSwiZW1haWwiOiJxaWxpbi5sb3VAbXlvYi5jb20iLCJqdGkiOiJlMWY5ODg2Ny02NjBlLTQ2ZjktYTlkZi01MTExMGRlY2ZjYWEifQ.uuCIJ4gz1a2l4qzIHIEWnWlFeAO4yvw6XJP1WONtY9BCpPacCsaXYg8qBi-LkpkDyZ5Ac9HN9npWQaTM9w8BwmfwmgJK075Uu2PL4u5zZ2mTGhfFVmOiqZDB3nQH0lo3ldxL-519vitnNcj8MV_z-gKzfDUYlL16yfMbSbkLaXXrA_A7u9GBu_XRsv-rjoiJnDATBYDjLBqH_f3KupKkUVpybl68chJCxL5m8mYldqDUe3aCOEtf8NoELKASWSh53S5OZbZGu7dNnIg8dfB_bsHu0MZMWEgOnt2BTNEjMYiLCuSrJB7_Ya28Sa8Q8ufQ9WePQ69JumPVRf2bperBSw

jira-token: Basic cWlsaW4ubG91QG15b2IuY29tOnQySVgxeURyU2VUeHBqc3hJMHhvMEM1Nw==

